databases:
  - name: payroll-management-db
    # ipAllowList: []
    databaseName: payroll-management
    user: app_user
    plan: free
    

services:
  - type: web
    name: payroll-management
    runtime: ruby
    env: ruby
    region: frankfurt
    plan: free
    autoDeploy: false
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: payroll-management-db
          property: connectionStrin
      - key: RAILS_MASTER_KEY
        sync: false