databases:
  - name: payroll_management_db
    # ipAllowList: []
    databaseName: payroll_management
    user: app_user
    plan: free
    

services:
  - type: web
    name: payroll_management
    runtime: ruby
    env: ruby
    region: frankfurt
    plan: free
    autoDeploy: false
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: payroll_management_db
          property: connectionStrin
      - key: RAILS_MASTER_KEY
        sync: false