databases:
  - name: postgres
    ipAllowList: []
    databaseName: payroll_management
    user: payroll_management

services:
  - type: web
    name: payroll_management
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionStrin
          plan: free
      - key: RAILS_MASTER_KEY
        sync: false